// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diuunrjsgxrjvclruvlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpdXVucmpzZ3hyanZjbHJ1dmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTc0MDIsImV4cCI6MjA2OTc3MzQwMn0.y7VB6IRhXs2lFwdplbHXsfjYw-GXoAaVZYrml-jCPAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});